name: OWASP ZAP Integration with GitHub Actions

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://testphp.vulnweb.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          
      - name: Push report to CSPM panel
        run: |
          curl --location --request POST 'https://${{ env.endpoint }}/api/v1/artifact/?tenant_id=${{ env.tenant_id }}&data_type=IAC&save_to_s3=false' --header 'Tenant-Id: ${{ inputs.tenant_id }}' --header 'Authorization: Bearer ${{ env.token }}' --form 'file=@"./scan_results.json"'
        env:
          token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzEwNDAwNzM3LCJqdGkiOiI4ZDRiNmQ3Y2IzODM0M2Y0YmRiMzc1MjIzNzM2NmI3MyIsImlzcyI6ImNzcG0uZGV2LmFjY3Vrbm94LmNvbSJ9.ZeHoaDVdF2vX70FWE7cxKfepst63hX1JeDOkvkPZicxXmYMv5CHi4wWZ1zbrF-5F0_2rV6Nb3dADC-qo4l99dbK4XmbzjSg4wgUKE6ObwoFUo17LuNpIv23_jpOOIkx2DvrSVZCDvAwLqQUCpBzZjoLr3nNWu_OUnHmiLN8D8ttz92EOhLOE7vjehXL5tMSoZYtHf5OzuvMjWxhAo1EJ94GxO0B5n-mg4qZXdm5_6AHwUdW9smZY_XQ38FlQhuEo21BkgP2DTwrpn9ZECYswJaK8atHBo7TaDwCbdaq8nLceLtZQYpXv61SAF_NdBQ9AOxyRuWQVQeFvyoM4wcfqUg"
          endpoint: "cspm.dev.accuknox.com"
          tenant_id: "1034"    
